const diseasesFirst = [
  'Abscess',
  'Bacteremia',
  'Cellulitis',
  'Clostridium difficile (C. diff)',
  'Cold Sores',
  'Coronavirus',
  'Diabetic Foot Infections',
  'Diarrhea',
  'E. Coli 0157: H7',
  'Ehrlichiosis',
  'Empyema',
  'Endocarditis',
  'Fever',
  'Flu',
  'Foodborne Illnesses',
  'Genital Herpes',
];
const diseasesSecond = [
  'Hepatitis A',
  'Hepatitis B',
  'Hepatitis C',
  'HIV',
  'Influenza',
  'Joint Infections',
  'Klebsiella pneumoniae',
  'Lyme Disease',
  'Measles',
  'MRSA',
  'Mumps',
  'Oral Thrush',
  'Osteomyelitis',
  'Peptic Ulcers',
  'Pneumonia',
  'Rashes',
];
const diseasesThird = [
  'Rheumatic Fever',
  'Sepsis',
  'Sexually Transmitted Diseases (STDs)',
  'Shingles',
  'Sinusitis',
  'Skin Infections',
  'Stasis Dermatitis',
  'Strep Throat',
  'Syphilis',
  'Tick-Borne Diseases',
  'Tuberculosis',
  'Upper Respiratory Infections',
  'Urinary Tract Infections',
  'Wound Infections',
  'Yeast Infections',
];
const insCompOne = [
  '1199 National Benefit Dund',
  'AARP',
  'Active Health',
  'Aetna',
  'Aetna Golden Medicare',
  'Alicare Inc.',
  'Teams Ters C/O Crossroads Health',
  'The Mail Handlers Benefit Plan',
  'Operating Engineers Local 825',
  'Principal Life Ins Co',
  'United Healthcare Community Plan',
  'Ameri Health processing center',
  'United Healthcare Community Plan',
  'American Progressive Med',
  'APWU Health Plan',
  'CHAMPVA',
  'Horizon BlueCross BlueShield',
];
const insCompTwo = [
  'Cigna Health Care',
  'Corsource',
  'Medicaid',
  'Oxford',
  'Qualcare',
  'Unified Lie Insurance Company',
  'Coventry Health Care',
  'Empire Medicare Service',
  'Golden  Rule Ins',
  'Great West Health Plan',
  'Health Care Partners',
  'Health First TPA',
  'Healthfirst',
  'Humana Claims',
  'Meritain Health',
  'Rail Road Medicare Services',
  'Secure Horizon',
];
const insCompThree = [
  'Wellcare',
  'IDA',
  'Fiserv Health',
  'GHI',
  'Local 804 WTF Magnacare',
  'Local Union',
  'Local 282 Welfare Trust Fund',
  'Local 825',
  'Local 1245 Health Fund',
  'Nipon Life Insurance Co of America',
  'PHCS',
  'Unicare',
  'Magnacare',
];

const idMail = 'idadvanced@gmail.com';
const idOff = 'idadvanced.office@gmail.com';
export {
  diseasesFirst,
  diseasesSecond,
  diseasesThird,
  insCompOne,
  insCompTwo,
  insCompThree,
  idMail,
  idOff,
};
